name: Newman API Tests

on:
  push:
    branches: ["main"]

jobs:
  run-api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installation de Node js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installation des librairies
        run: npm install     

      - name: Lancement du serveur
        run: |
          nohup node server.js > server.log 2>&1 &
          sleep 5

      - name: Installation de Newman + HTML Extra Reporter
        run: npm install -g newman newman-reporter-html

      - name: Lancement de Newman
        run: |
          newman run "./postman/collection.postman_collection.json" \
          -e "./postman/environnement.postman_environment.json" \
          --iteration-data "./postman/iteration.json" \
          --reporter-htmlextra-export "./reports/RapportNewman.html" 

      - name: upload HTML test report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: newman-test-report
          path: reports/RapportNewman.html
      - name: Add HTML report link
        run: |
          echo "### Rapport newman generÃ©" >> $GITHUB_STEP_SUMMARY
          echo "Telecharger le rapport depuis la section **Artifacts -> newman-test-report**" >> $GITHUB_STEP_SUMMARY