name: Newman API Tests

on:
  push:
    branches: ["main"]

jobs:
  run-api-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Installation de Node js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installation des librairies
        run: npm install     

      - name: Lancement du serveur
        run: |
          nohup node server.js > server.log 2>&1 &
          sleep 5

      - name: Installation de Newman + HTML Extra Reporter
        run: npm install -g newman newman-reporter-html

      - name: Lancement de Newman
        run: |
          newman run "./postman/collection.postman_collection.json" \
          -e "./postman/environnement.postman_environment.json" \
          --iteration-data "./postman/iteration.json" \


